Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "docker"
  config.vm.network "forwarded_port", guest: 8080, host: 1234 # docker-compose for wordpress
  config.vm.network "forwarded_port", guest: 8081, host: 1235 # ngnix
end
